version: 2
jobs:
  prestashop:
    environment:
      PS_DEV_MODE: 1 # The constant _PS_MODE_DEV_ will be set at true (default value: 0)
      # PS_HOST_MODE: The constant _PS_HOST_MODE_ will be set at true. Useful to simulate a PrestaShop Cloud environment. (default value: 0)
      # PS_DEMO_MODE: 0 # The constant _PS_DEMO_MODE_ will be set at true. Use it to create a demonstration shop. (default value: 0)
      DB_SERVER: 127.0.0.1 # If set, the external MySQL database will be used instead of the volatile internal one (default value: localhost)
      DB_PORT: 3306
      DB_USER: root # Override default MySQL user (default value: root)
      DB_PASSWD: admin # Override default MySQL password (default value: admin)
      DB_PREFIX: ps_ # Override default tables prefix (default value: ps_)
      DB_NAME: prestashop # Override default database name (default value: prestashop)
      PS_INSTALL_AUTO: 0 # The installation will be executed. Useful to initialize your image faster. In some configurations, you may need to set PS_DOMAIN or PS_HANDLE_DYNAMIC_DOMAIN as well. (Please note that PrestaShop can be installed automatically from PS 1.5)
      PS_ERASE_DB: 0 # Only with PS_INSTALL_AUTO=1. Drop and create the mysql database. All previous mysql data will be lost (default value: 0)
      PS_DOMAIN: localhost:8082 # When installing automatically your shop, you can tell the shop how it will be reached. For advanced users only (no default value)
      PS_LANGUAGE: fr # Change the default language installed with PrestaShop (default value: en)
      PS_COUNTRY: FR # Change the default country installed with PrestaShop (default value: GB)
      # PS_ALL_LANGUAGES: Install all the existing languages for the current version. (default value: 0)
      # PS_FOLDER_ADMIN: Change the name of the admin folder (default value: admin. But will be automatically changed later)
      # PS_FOLDER_INSTALL: Change the name of the install folder (default value: install. But must be changed anyway later)
      # PS_ENABLE_SSL: Enable SSL at PrestaShop installation. (default value: 0)
    docker:
      - image: prestashop/prestashop:latest
      - image: mariadb:latest
        environment:
          MYSQL_ROOT_PASSWORD: admin
          MYSQL_DATABASE: prestashop
    steps:
      - checkout
      # https://circleci.com/docs/2.0/databases/
      - run:
          name: Install dockerize
          command: wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
          environment:
            DOCKERIZE_VERSION: v0.6.1
      - run:
          name: Waiting for MySQL to be ready
          command: dockerize -wait tcp://localhost:3306 -timeout 1m
      - run:
          name: Install PrestaShop
          command: >
            php /var/www/html/$PS_FOLDER_INSTALL/index_cli.php
            --domain="$PS_DOMAIN"
            --db_server=$DB_SERVER:$DB_PORT
            --db_name="$DB_NAME"
            --db_user=$DB_USER
            --db_password=$DB_PASSWD
            --prefix="$DB_PREFIX"
            --firstname="John"
            --lastname="Doe"
            --password=$ADMIN_PASSWD
            --email="$ADMIN_MAIL"
            --language=$PS_LANGUAGE
            --country=$PS_COUNTRY
            --all_languages=$PS_ALL_LANGUAGES
            --newsletter=0
            --send_email=0
            --ssl=0
      # https://devdocs.prestashop.com/1.7/modules/concepts/commands/
      - run:
          name: Install CoopCycle module
          command: |
            mv ./prestashop /var/www/html/modules/coopcycle
            ls -l /var/www/html/modules/
            cd /var/www/html
            php bin/console prestashop:module install coopcycle

workflows:
  version: 2
  prestashop:
    jobs:
      - prestashop
