notifications:
  email: false

sudo: required

matrix:
  fast_finish: true

language: php
php:
  - '7.3.12'

cache:
  apt: true
  directories:
    - $HOME/.composer/cache/files

before_script:
  - composer install --prefer-dist

script:
  - phpunit
